### ISSUE TITLE
Where is the document that says how to use the tool?

### ISSUE THREAD

**Issue by 21-ko** [gdkchan/MGSDATool#8]
After building the project, I dragged and dropped the file, but it didn't work.

**Comment by 21-ko** [comment]
Oh, I found it
It was written in the command

**Comment by 21-ko** [comment]
tool [command] [game] movie.dat [folder]

Examples:

tool -e -mgs<3|4|ts> movie.dat folder  Extracts subtitles from a movie.dat file
tool -i -mgs<3|4|ts> movie.dat folder  Creates the movie.dat from a folder

**Comment by Azooz5897i** [comment]
Please, what is the SpeechTool command to unzip the file?
